source 'https://rubygems.org'

gem 'rails', '5.0'

# Use Puma as the app server
gem 'puma', '3.4.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
gem 'active_model_serializers', '0.10.2'
gem 'devise', '4.2.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '0.4.0'

group :development, :test do
  gem 'mysql2', '0.4.4'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '9.0.5'
  gem 'rspec-rails', '3.5.1'
  gem 'factory_girl_rails', '4.7.0'
end

group :development do
  gem 'listen', '3.0.8'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '1.7.2'
  gem 'spring-watcher-listen', '2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
